'use client'
import { isAxiosError } from 'axios'
import { Activity as ActivityIcon, LogIn, RefreshCw, Search } from 'lucide-react'
import Link from 'next/link'
import { useSearchParams } from 'next/navigation'
import { useQuery } from '@tanstack/react-query'
import { CatalogPagination } from '@/features/catalog-pagination/ui/catalog-pagination'
import { auditApi } from '@/entities/audit/api/audit.api'
import type { AuditEntry } from '@/entities/audit/types/audit-entry.types'
function TimelineItem({ entry }: { entry: AuditEntry }) { const date = new Intl.DateTimeFormat('en', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(entry.occurredAt)); return <article className='audit-item'><div className='audit-item__rail'><span /><i /></div><div className='audit-item__body'><div className='audit-item__meta'><span>{entry.sourceService}</span><time dateTime={entry.occurredAt}>{date}</time></div><h2>{entry.eventType}</h2><p>Aggregate <code>{entry.aggregateId}</code></p></div></article> }
export default function ActivityPage() { const params = useSearchParams(); const aggregateId = params.get('aggregateId') ?? undefined; const page=Number(params.get('page')??'1'); const { data, error, isPending, refetch } = useQuery({ queryKey: ['audit', aggregateId, page], queryFn: () => auditApi.list({ aggregateId, page }) }); const signIn = isAxiosError(error) && error.response?.status === 401; return <div className='page'><header className='page-heading'><div><p className='eyebrow'>Audit service</p><h1>Activity</h1></div><p className='page-heading__description'>A chronological record of change events emitted by the platform.</p></header><form className='audit-filter'><label htmlFor='aggregateId'>Filter by aggregate ID</label><div><Search aria-hidden='true' size={16}/><input defaultValue={aggregateId} id='aggregateId' name='aggregateId' placeholder='Employee or department ID' type='search'/></div></form>{isPending ? <section aria-busy='true' className='empty-state'><div className='empty-state__icon'><ActivityIcon aria-hidden='true' size={21}/></div><h2>Loading activity</h2><p>Retrieving the latest audit events.</p></section> : null}{signIn ? <section className='empty-state'><div className='empty-state__icon'><LogIn aria-hidden='true' size={21}/></div><h2>Sign in to view activity</h2><p>Audit records are available through an authenticated workspace session.</p><Link className='retry-button' href='/login'><LogIn aria-hidden='true' size={16}/>Continue to sign in</Link></section> : null}{error && !signIn ? <section className='empty-state' role='alert'><div className='empty-state__icon'><ActivityIcon aria-hidden='true' size={21}/></div><h2>Activity is unavailable</h2><p>Check that the audit service is running, then try again.</p><button className='retry-button' onClick={() => refetch()} type='button'><RefreshCw aria-hidden='true' size={16}/>Retry request</button></section> : null}{data?.items.length === 0 ? <section className='empty-state'><div className='empty-state__icon'><ActivityIcon aria-hidden='true' size={21}/></div><h2>No activity yet</h2><p>Events will appear here when platform services record organizational changes.</p></section> : null}{data?.items.length ? <section aria-label='Audit timeline' className='audit-timeline'>{data.items.map(entry => <TimelineItem entry={entry} key={entry.id}/>)}</section> : null}{data?<CatalogPagination hasNext={data.hasNext} page={data.page} total={data.total}/>:null}</div> }
