{
  "type": "record",
  "name": "LocationCreated",
  "namespace": "ds.directory",
  "fields": [
    {
      "name": "LocationId",
      "type": {
        "type": "string",
        "logicalType": "uuid"
      }
    },
    {
      "name": "Name",
      "type": "string"
    },
    {
      "name": "Street",
      "type": "string"
    },
    {
      "name": "City",
      "type": "string"
    },
    {
      "name": "Country",
      "type": "string"
    },
    {
      "name": "Timezone",
      "type": "string"
    }
  ]
}
