'use client'
import { isAxiosError } from 'axios'
import { Building2, LogIn, Plus, RefreshCw } from 'lucide-react'
import Link from 'next/link'
import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { DepartmentForm } from '@/features/department-create/ui/department-form'
import { directoryCatalogApi } from '@/entities/directory/api/catalog.api'
import { departmentsApi } from '@/entities/departments/api/departments.api'
import type { ParentDepartment } from '@/entities/departments/types/department.types'
import DepartmentCard from '@/entities/departments/ui/department.card'
function flatten(items:ParentDepartment[]):{id:string;name:string;path:string}[]{return items.flatMap(d=>[{id:d.id,name:d.name,path:d.path},...flatten(d.children??[])])}
export default function DepartmentsPage(){const[creating,setCreating]=useState(false);const q=useQuery({queryKey:['departments','roots'],queryFn:()=>departmentsApi.getParentDepartments()});const locations=useQuery({queryKey:['locations','form'],queryFn:()=>directoryCatalogApi.locations({isActive:true,size:200}),enabled:creating});const login=isAxiosError(q.error)&&q.error.response?.status===401;return <div className='page'><header className='page-heading'><div><p className='eyebrow'>Directory service</p><h1>Organization</h1></div><p className='page-heading__description'>The department hierarchy is read from the directory service through the authenticated application boundary.</p></header><button className='primary-action' onClick={()=>setCreating(true)} type='button'><Plus aria-hidden='true' size={16}/>New department</button>{creating&&locations.data&&q.data?<DepartmentForm departments={flatten(q.data)} locations={locations.data.items} onClose={()=>setCreating(false)}/>:null}{creating&&locations.isPending?<section className='empty-state'><h2>Loading locations</h2><p>Retrieving active locations for this department.</p></section>:null}{q.isPending?<section aria-busy='true' className='empty-state'><div className='empty-state__icon'><Building2 aria-hidden='true' size={21}/></div><h2>Loading organization structure</h2><p>The directory service is responding with the current department hierarchy.</p></section>:null}{login?<section className='empty-state'><div className='empty-state__icon'><LogIn aria-hidden='true' size={21}/></div><h2>Sign in to view the organization</h2><p>Your workspace session gives the server permission to retrieve protected directory data.</p><Link className='retry-button' href='/login'><LogIn aria-hidden='true' size={16}/>Continue to sign in</Link></section>:null}{q.error&&!login?<section className='empty-state' role='alert'><h2>Organization data is unavailable</h2><p>Check that the local platform is running, then try again.</p><button className='retry-button' onClick={()=>q.refetch()} type='button'><RefreshCw aria-hidden='true' size={16}/>Retry request</button></section>:null}{q.data?<div className='department-grid'>{q.data.map(d=><DepartmentCard department={d} key={d.id}/>)}</div>:null}</div>}
