'use client'
import { zodResolver } from '@hookform/resolvers/zod'
import { useMutation, useQueryClient } from '@tanstack/react-query'
import { LoaderCircle } from 'lucide-react'
import { useForm } from 'react-hook-form'
import { z } from 'zod'
import { directoryCatalogApi } from '@/entities/directory/api/catalog.api'
const schema=z.object({name:z.string().trim().min(2,'Enter a location name.'),street:z.string().trim().min(2,'Enter a street.'),city:z.string().trim().min(2,'Enter a city.'),country:z.string().trim().min(2,'Enter a country.'),timezone:z.string().trim().min(2,'Enter an IANA timezone.')}); type Values=z.infer<typeof schema>
export function LocationForm({onClose}:{onClose:()=>void}){const qc=useQueryClient();const form=useForm<Values>({resolver:zodResolver(schema),mode:'onSubmit',defaultValues:{name:'',street:'',city:'',country:'',timezone:''}});const m=useMutation({mutationFn:directoryCatalogApi.createLocation,onSuccess:async()=>{await qc.invalidateQueries({queryKey:['locations']});onClose()},onError:()=>form.setError('root',{message:'Location could not be created. Check your access and try again.'})});return <section className='employee-form-panel'><div className='employee-form-panel__heading'><div><p className='eyebrow'>Directory administration</p><h2>New location</h2></div><button aria-label='Close form' className='icon-button' onClick={onClose} type='button'>×</button></div><form className='employee-form' onSubmit={form.handleSubmit(v=>m.mutate(v))}>{(['name','street','city','country','timezone'] as const).map(f=><label className='form-field' key={f}><span>{f==='timezone'?'IANA timezone':f[0].toUpperCase()+f.slice(1)}</span><input {...form.register(f)} placeholder={f==='timezone'?'Europe/London':undefined}/>{form.formState.errors[f]?.message?<small role='alert'>{form.formState.errors[f]?.message}</small>:null}</label>)}{form.formState.errors.root?<p className='form-error' role='alert'>{form.formState.errors.root.message}</p>:null}<button className='form-submit' disabled={m.isPending} type='submit'>{m.isPending?<LoaderCircle aria-hidden='true' className='animate-spin' size={16}/>:null}Create location</button></form></section>}
