'use client'
import { zodResolver } from '@hookform/resolvers/zod'
import { useMutation, useQueryClient } from '@tanstack/react-query'
import { LoaderCircle } from 'lucide-react'
import { useForm } from 'react-hook-form'
import { z } from 'zod'
import { mutationErrorMessage } from '@/shared/api/mutation-error'
import { applyEnvelopeErrors } from '@/shared/api/validation-error'
import { directoryCatalogApi } from '@/entities/directory/api/catalog.api'
const schema=z.object({name:z.string().trim().min(2,'Enter a position name.'),description:z.string().trim().max(1000,'Keep the description under 1000 characters.').optional(),departmentIds:z.array(z.string().uuid()).min(1,'Choose at least one department.')});type Values=z.infer<typeof schema>;type Department={id:string;name:string;path:string}
export function PositionForm({departments,onClose}:{departments:Department[];onClose:()=>void}){const qc=useQueryClient();const form=useForm<Values>({resolver:zodResolver(schema),mode:'onSubmit',defaultValues:{name:'',description:'',departmentIds:[]}});const m=useMutation({mutationFn:directoryCatalogApi.createPosition,onSuccess:async()=>{await qc.invalidateQueries({queryKey:['positions']});onClose()},onError:error=>{if(!applyEnvelopeErrors(error,['name','description','departmentIds'],form.setError))form.setError('root',{message:mutationErrorMessage(error, 'Position')})}});return <section className='employee-form-panel'><div className='employee-form-panel__heading'><div><p className='eyebrow'>Directory administration</p><h2>New position</h2></div><button aria-label='Close form' className='icon-button' onClick={onClose} type='button'>×</button></div><form className='employee-form' onSubmit={form.handleSubmit(v=>m.mutate(v))}><label className='form-field'><span>Position name</span><input {...form.register('name')} placeholder='Senior product designer'/>{form.formState.errors.name?.message?<small role='alert'>{form.formState.errors.name.message}</small>:null}</label><label className='form-field'><span>Description <em>Optional</em></span><input {...form.register('description')} placeholder='Owns the end-to-end product experience.'/></label><fieldset className='department-field'><legend>Available in departments</legend><div>{departments.map(d=><label key={d.id}><input type='checkbox' value={d.id} {...form.register('departmentIds')}/><span>{d.name}</span><small>/{d.path}</small></label>)}</div>{form.formState.errors.departmentIds?.message?<small role='alert'>{form.formState.errors.departmentIds.message}</small>:null}</fieldset>{form.formState.errors.root?<p className='form-error' role='alert'>{form.formState.errors.root.message}</p>:null}<button className='form-submit' disabled={m.isPending} type='submit'>{m.isPending?<LoaderCircle aria-hidden='true' className='animate-spin' size={16}/>:null}Create position</button></form></section>}
