#!/usr/bin/env python3
"""Generates slo.yml: multiwindow, multi-burn-rate SLO rules per user journey.

Edit JOURNEYS / the targets below and re-run:  python3 generate-slo-rules.py > slo.yml

Method: Google SRE Workbook, "Alerting on SLOs". A burn rate of 1 spends exactly the error
budget over the SLO period; page at 14.4x over 1h (2% of a 30-day budget gone), ticket at 6x
over 6h. Each alert also requires the short window to be burning, so it stops firing soon after
the problem does.
"""

# name, service_name label, http_route regex, method regex
JOURNEYS = [
    ("sign-in", "auth-service", "/?auth/login", "POST"),
    ("hire", "employee-service", "/?api/employees", "POST"),
    ("grant-currency", "rewards-service", "/?api/rewards/grants", "POST"),
    ("search", "search-service", "/?api/search", "GET"),
]
WINDOWS = ["5m", "30m", "1h", "6h"]
AVAILABILITY_TARGET = 0.995   # non-5xx; 4xx (incl. 429) are the caller's, not a failure
LATENCY_TARGET = 0.95         # answered within LATENCY_LE seconds
LATENCY_LE = "0.5"            # must be an existing histogram bucket boundary
FAST, SLOW = 14.4, 6.0


def selector(metric, service, route, method, extra=""):
    return (f'{metric}{{service_name="{service}",http_route=~"{route}",'
            f'http_request_method=~"{method}"{extra}}}')


out = ["# GENERATED by generate-slo-rules.py - edit the script, not this file.", "groups:"]

out += ["  - name: slo-sli", "    rules:"]
for name, svc, route, method in JOURNEYS:
    for w in WINDOWS:
        total = selector("http_server_request_duration_seconds_count", svc, route, method)
        bad = selector("http_server_request_duration_seconds_count", svc, route, method,
                       ',http_response_status_code=~"5.."')
        fast = selector("http_server_request_duration_seconds_bucket", svc, route, method,
                        f',le="{LATENCY_LE}"')
        allb = selector("http_server_request_duration_seconds_bucket", svc, route, method, ',le="+Inf"')
        out += [
            f"      - record: journey:availability_error_ratio:rate{w}",
            f"        expr: (sum(rate({bad}[{w}])) or vector(0)) / (sum(rate({total}[{w}])) > 0)",
            f"        labels: {{journey: {name}}}",
            f"      - record: journey:latency_slow_ratio:rate{w}",
            f"        expr: 1 - (sum(rate({fast}[{w}])) / (sum(rate({allb}[{w}])) > 0))",
            f"        labels: {{journey: {name}}}",
        ]

out += ["  - name: slo-burn-alerts", "    rules:"]
for kind, target, label in [
    ("availability_error_ratio", AVAILABILITY_TARGET, "Availability"),
    ("latency_slow_ratio", LATENCY_TARGET, f"Latency (<= {LATENCY_LE}s)"),
]:
    budget = round(1 - target, 6)
    cap = kind.split("_")[0].capitalize()
    out += [
        f"      - alert: Journey{cap}BudgetBurnFast",
        f"        expr: journey:{kind}:rate1h > {FAST} * {budget} and journey:{kind}:rate5m > {FAST} * {budget}",
        "        labels: {severity: page}",
        "        annotations:",
        f'          summary: "{label} of journey {{{{ $labels.journey }}}} is burning its error budget {FAST}x too fast"',
        f'          description: "SLO {target:.1%}. At this rate 2% of the 30-day budget is gone in an hour."',
        f"      - alert: Journey{cap}BudgetBurnSlow",
        f"        expr: journey:{kind}:rate6h > {SLOW} * {budget} and journey:{kind}:rate30m > {SLOW} * {budget}",
        "        labels: {severity: ticket}",
        "        annotations:",
        f'          summary: "{label} of journey {{{{ $labels.journey }}}} is steadily overspending its error budget"',
        f'          description: "SLO {target:.1%}. Burning {SLOW}x over 6h: a slow leak, not an outage."',
    ]

print("\n".join(out))
