'use client'
import { isAxiosError } from 'axios'
import { LogIn, MapPin, Plus, RefreshCw } from 'lucide-react'
import Link from 'next/link'
import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { LocationForm } from '@/features/directory-create/ui/location-form'
import { directoryCatalogApi } from '@/entities/directory/api/catalog.api'
export default function LocationsPage(){const [creating,setCreating]=useState(false);const {data,error,isPending,refetch}=useQuery({queryKey:['locations'],queryFn:()=>directoryCatalogApi.locations({isActive:true})});const login=isAxiosError(error)&&error.response?.status===401;return <div className='page'><header className='page-heading'><div><p className='eyebrow'>Directory service</p><h1>Locations</h1></div><p className='page-heading__description'>Active offices and locations represented in the organization.</p></header><button className='primary-action' onClick={()=>setCreating(true)} type='button'><Plus aria-hidden='true' size={16}/>New location</button>{creating?<LocationForm onClose={()=>setCreating(false)}/>:null}{isPending?<section aria-busy='true' className='empty-state'><h2>Loading locations</h2><p>Retrieving the location catalogue.</p></section>:null}{login?<section className='empty-state'><h2>Sign in to view locations</h2><p>This catalogue is available through an authenticated workspace session.</p><Link className='retry-button' href='/login'><LogIn aria-hidden='true' size={16}/>Continue to sign in</Link></section>:null}{error&&!login?<section className='empty-state' role='alert'><h2>Locations are unavailable</h2><p>Check the directory service and try again.</p><button className='retry-button' onClick={()=>refetch()} type='button'><RefreshCw aria-hidden='true' size={16}/>Retry request</button></section>:null}{data?.items.length===0?<section className='empty-state'><h2>No active locations</h2><p>Locations will appear here when they are added to the directory.</p></section>:null}{data?.items.length?<section className='catalog-grid'>{data.items.map(l=><article className='catalog-card' key={l.id}><MapPin aria-hidden='true' size={19}/><h2>{l.name}</h2><p>{l.street}, {l.city}, {l.country}</p><div className='catalog-tags'><span>{l.timezone}</span></div></article>)}</section>:null}</div>}
