'use client'
import { zodResolver } from '@hookform/resolvers/zod'
import { useMutation, useQueryClient } from '@tanstack/react-query'
import { LoaderCircle } from 'lucide-react'
import { useForm } from 'react-hook-form'
import { z } from 'zod'
import { mutationErrorMessage } from '@/shared/api/mutation-error'
import { departmentsApi } from '@/entities/departments/api/departments.api'
import type { Location } from '@/entities/directory/types/catalog.types'
const schema=z.object({name:z.string().trim().min(2,'Enter a department name.'),identifier:z.string().trim().min(2,'Enter an identifier.').regex(/^[a-z0-9-]+$/,'Use lowercase letters, numbers, and hyphens.'),parentDepartmentId:z.string().uuid().optional().or(z.literal('')),locationsIds:z.array(z.string().uuid()).min(1,'Choose at least one location.')});type Values=z.infer<typeof schema>;type Department={id:string;name:string;path:string}
export function DepartmentForm({departments,locations,onClose}:{departments:Department[];locations:Location[];onClose:()=>void}){const qc=useQueryClient();const f=useForm<Values>({resolver:zodResolver(schema),mode:'onSubmit',defaultValues:{name:'',identifier:'',parentDepartmentId:'',locationsIds:[]}});const m=useMutation({mutationFn:departmentsApi.createDepartment,onSuccess:async()=>{await qc.invalidateQueries({queryKey:['departments']});onClose()},onError:error=>f.setError('root',{message:mutationErrorMessage(error, 'Department')})});return <section className='employee-form-panel'><div className='employee-form-panel__heading'><div><p className='eyebrow'>Directory administration</p><h2>New department</h2></div><button aria-label='Close form' className='icon-button' onClick={onClose} type='button'>×</button></div><form className='employee-form' onSubmit={f.handleSubmit(v=>m.mutate({...v,parentDepartmentId:v.parentDepartmentId||undefined}))}><label className='form-field'><span>Name</span><input {...f.register('name')} placeholder='Product design'/>{f.formState.errors.name?.message?<small role='alert'>{f.formState.errors.name.message}</small>:null}</label><label className='form-field'><span>Identifier</span><input {...f.register('identifier')} placeholder='product-design'/>{f.formState.errors.identifier?.message?<small role='alert'>{f.formState.errors.identifier.message}</small>:null}</label><label className='form-field'><span>Parent department <em>Optional</em></span><select {...f.register('parentDepartmentId')}><option value=''>No parent department</option>{departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><fieldset className='department-field'><legend>Operating locations</legend><div>{locations.map(l=><label key={l.id}><input type='checkbox' value={l.id} {...f.register('locationsIds')}/><span>{l.name}</span><small>{l.city}, {l.country}</small></label>)}</div>{f.formState.errors.locationsIds?.message?<small role='alert'>{f.formState.errors.locationsIds.message}</small>:null}</fieldset>{f.formState.errors.root?<p className='form-error' role='alert'>{f.formState.errors.root.message}</p>:null}<button className='form-submit' disabled={m.isPending} type='submit'>{m.isPending?<LoaderCircle aria-hidden='true' className='animate-spin' size={16}/>:null}Create department</button></form></section>}
