'use client'

import { isAxiosError } from 'axios'
import { Building2, LogIn, Plus, RefreshCw, Repeat2, UsersRound } from 'lucide-react'
import Link from 'next/link'
import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'

import { directoryCatalogApi } from '@/entities/directory/api/catalog.api'
import { employeesApi } from '@/entities/employees/api/employees.api'
import type { Employee } from '@/entities/employees/types/employee.types'
import { EmployeeForm } from '@/features/employee-lifecycle/ui/employee-form'

function initials(name: string) { return name.split(' ').map(part => part[0]).slice(0, 2).join('').toUpperCase() }
function PersonCard({ employee, onTransfer }: { employee: Employee; onTransfer: (employee: Employee) => void }) { return <article className='person-card'><div className='person-card__avatar'>{initials(employee.fullName)}</div><div className='person-card__top'><div><h2>{employee.fullName}</h2><a href={`mailto:${employee.email}`}>{employee.email}</a></div><span className='status-badge'>{employee.status}</span></div><dl><div><dt>Position</dt><dd>{employee.positionName}</dd></div><div><dt>Department</dt><dd>{employee.departmentName}</dd></div><div><dt>Joined</dt><dd>{new Intl.DateTimeFormat('en', { dateStyle: 'medium' }).format(new Date(employee.hiredAt))}</dd></div></dl><button className='person-card__action' onClick={() => onTransfer(employee)} type='button'><Repeat2 aria-hidden='true' size={15}/>Transfer</button></article> }
export default function PeoplePage() { const [form, setForm] = useState<{ employee?: Employee } | null>(null); const people = useQuery({ queryKey: ['employees'], queryFn: () => employeesApi.list() }); const positions = useQuery({ queryKey: ['positions', 'active'], queryFn: () => directoryCatalogApi.positions({ isActive: true, size: 200 }), enabled: Boolean(form) }); const requiresSignIn = isAxiosError(people.error) && people.error.response?.status === 401
 return <div className='page'><header className='page-heading'><div><p className='eyebrow'>Employee service</p><h1>People</h1></div><div className='page-heading__actions'><p className='page-heading__description'>People records are retrieved through the authenticated service boundary.</p><button className='primary-action' onClick={() => setForm({})} type='button'><Plus aria-hidden='true' size={16}/>Hire employee</button></div></header>{form && positions.data ? <EmployeeForm employee={form.employee ? { id: form.employee.id, name: form.employee.fullName } : undefined} onClose={() => setForm(null)} positions={positions.data.items}/>:null}{form && positions.isPending ? <section className='empty-state'><h2>Loading organization options</h2><p>Retrieving active positions and their department links.</p></section>:null}{people.isPending ? <section aria-busy='true' className='empty-state'><div className='empty-state__icon'><UsersRound aria-hidden='true' size={21}/></div><h2>Loading people</h2><p>Retrieving the employee directory.</p></section> : null}{requiresSignIn ? <section className='empty-state'><div className='empty-state__icon'><LogIn aria-hidden='true' size={21}/></div><h2>Sign in to view people</h2><p>Your workspace session authorizes this protected employee directory.</p><Link className='retry-button' href='/login'><LogIn aria-hidden='true' size={16}/>Continue to sign in</Link></section> : null}{people.error && !requiresSignIn ? <section className='empty-state' role='alert'><div className='empty-state__icon'><Building2 aria-hidden='true' size={21}/></div><h2>People data is unavailable</h2><p>Check that the employee service is running, then try again.</p><button className='retry-button' onClick={() => people.refetch()} type='button'><RefreshCw aria-hidden='true' size={16}/>Retry request</button></section> : null}{people.data?.length === 0 ? <section className='empty-state'><div className='empty-state__icon'><UsersRound aria-hidden='true' size={21}/></div><h2>No people yet</h2><p>Employee records will appear here after they are added to the platform.</p></section> : null}{people.data?.length ? <section aria-label='People directory' className='people-grid'>{people.data.map(employee => <PersonCard employee={employee} key={employee.id} onTransfer={employee => setForm({ employee })}/>)}</section> : null}</div> }
